### ISSUE TITLE
Fail to triangulate

### ISSUE THREAD

**Issue by masklu** [ivanfratric/polypartition#36]
Hi, i try to triangulate a simple polygon but It fails
my code
TPPLPoly tp;
    tp.Init(7);
    tp[0].x = 25;tp[0].y = -25;
    tp[1].x = 0;tp[1].y = -25;
    tp[2].x = -25;tp[2].y = -25;
    tp[3].x = -25;tp[3].y = 0;
    tp[4].x = -25;tp[4].y = 25;
    tp[5].x = 0;tp[5].y = 25;
    tp[6].x = 25;tp[6].y = 25;
    TPPLPartition pp;
    int ret = pp.Triangulate_EC(&tp, &resultarray);
    qDebug()<< resultarray.size() << ret;

**Comment by ivanfratric** [comment]
Possibly the polygon ordering is wrong (clockwise vs. counter-clockwise). Try calling tp.SetOrientation(TPPL_CCW) before calling Triangulate_EC.

**Comment by aaronfranke** [comment]
Here is the polygon in the form of a test case text file (with 50 added to each axis to make all values positive): [issue-36.txt](https://github.com/ivanfratric/polypartition/files/5779411/issue-36.txt)

This does indeed fail, but the problem is that the polygon is defined counter-clockwise. Here is a fixed version of the same polygon, with the order of the points reversed so that it's clockwise: [issue-36-clockwise.txt](https://github.com/ivanfratric/polypartition/files/5779440/issue-36-clockwise.txt)

I think this issue can be closed, since I don't think it's a bug.
